import = [
    "~/.config/alacritty/themes/themes/alabaster.toml"
]

[colors]
draw_bold_text_with_bright_colors = false

[env]
TERM = "xterm-256color"

[font]
size = 20
#use_thin_strokes = true

[font.glyph_offset]
x = 1
y = 1

[font.offset]
x = 0
y = 1

[scrolling]
history = 10000
multiplier = 3

[window]
decorations = "none"
startup_mode = "Fullscreen"

[window.padding]
x = 3
y = 3
